version: "3.8"

services:
  mongo:
    image: mongo:5.0
    container_name: mongo
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db
      - ./mongo-init:/docker-entrypoint-initdb.d

  scraper:
    build: .
    container_name: navcanada_scraper
    environment:
      - MONGO_URI=mongodb://mongo:27017/
    depends_on:
      - mongo

volumes:
  mongo-data:
